# Numpy

[NumPy](https://numpy.org/) это open-source модуль для python, который предоставляет общие математические и числовые операции.

NumPy - один из ключевых модулей в экосистеме Python, в том числе при решении задач машинного обучения и искусственного интеллекта.

NumPy является наследником Numeric и NumArray. Основан NumPy на библиотеке LAPAC, которая написана на Fortran. Когда-то numpy была частью SciPy. Да, это напоминает мыльную оперу. 

Мы подробно разбираем особенности библиотеки, так как на работе с ней основаны все остальные библиотеки, работающие с искусственным интеллектом.

Текст урока опирается на небольшой, но полезный [мануал](https://sites.engineering.ucsb.edu/~shell/che210d/numpy.pdf).

## Установка

Если вы используете Google Colab, то numpy уже установлен на виртуальном сервере и вы можете им пользоваться.

Если вы открыли собственный ноутбук, то можете воспользоваться командой установки, записанной через восклицательный знак


```
!comand
```
Так запущенная команда в среде ipy вызывает системную команду pip, которая сама установит данный модуль в вашу виртуальную среду. 

Обратите внимание, что каждый ноутбк имеет свой набор используемых библиотек и системных установок. 


In [ ]:
!pip install numpy

## Подключение

Для подключения модулей в Python используется команда `import` или её вариации. В случае с numpy есть традиционная и привычная всем команда импорта с использованием алиаса (as) np

Алиас - это встроенная команда интерпретатора для сокращения команд и их последовательностей.

In [ ]:
# классический вариант
import numpy

In [1]:
# традиционный вариант 
import numpy as np

При таком импорте к любым командам из модуля numpy придётся дописывать название модуля

```
numpy.comand
np.comand
```
Есть другой вариант, в котором можно использовать только команду без указания модуля. Но так как в разных модулях могут быть одинаковые функции, использовать такой вариант не рекомендуется.


In [ ]:
from numpy import *

## Особые константы

Numpy реализует несколько особых значнений через контстанты. Например:

In [ ]:
np.NaN
# None
# not a number - Не число

nan

In [ ]:
np.Inf
# infinity - бесконечно 

inf

## Массивы

Главная особенность и элемент, с которым необходимо работать, в numpy - это массивы. Создаются массивы разными способами, которые мы сейчас разберём. 

При этом всем элементы в array должны быть одного типа, что отличает его от классического списка (list) Python. 

In [2]:
import numpy as np

a = np.array([1, 2, 3, 4], int)

print('Array:', a)
print('Тип: ',type(a))
# обратное преобразование
print(a.tolist())

Array: [1 2 3 4]
Тип:  <class 'numpy.ndarray'>
[1, 2, 3, 4]


In [ ]:
# показыаем, что можно также работать с np.array, как и с обычным list

print('1: ', a[0])
print('2: ', a[1:3])
print('3: ', a[-1])
a[0] = 5
print('4: ', a[0])

1:  1.0
2:  [2. 3.]
3:  4.0
4:  5.0


### Многомерные массивы 

Большая ценность numpy в том, что можно работать и многомерными массивами. Например, любое изображение - как минимум двумерный массив. А при обучении нейронных сетей для работы с компьютерным зрением используются по сути четырёхмерные массивы.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]], int)
# [список всех строк]
print('0: ', a)
print('1: ', a[0,0])
print('2: ', a[1,0])
print('3: ', a[0,1])

0:  [[1 2 3]
 [4 5 6]]
1:  1
2:  4
3:  2


In [ ]:
# Задание классное работы 1
# Создать массив нампай 3 на 3
# Вывести элементы главно диагонали
1 2 3
9 0 8
7 8 5

1 0 5

In [6]:
# срезы (сленг - слайсы) с двмерным массивом
# [строки, столбцы]
# [start:stop-1:step,start:stop-1:step]
a = np.array([[1, 2, 3], [4, 5, 6]], int)

print(a)
print()
print('4: ', a[1,:])
print('5: ', a[:,2])
print('6: ', a[-1:, -2:])

[[1 2 3]
 [4 5 6]]

4:  [4 5 6]
5:  [3 6]
6:  [[5 6]]


In [ ]:
# Задание классное работы 1
# Создать массив нампай 3 на 3
# Вывести элементы главно диагонали
1 2 3
9 0 8
7 8 5

1 0 5

# Задание 2
# Девочки - элементы второго столбца всех строк (с индексом 1)
# Мальчики - элементов всех столбцов второй строки

### Характеристики объектов numpy

In [ ]:
# размеры
a.shape
# shape - возвращает кортеж (строки, столбцов)

(2, 3)

In [ ]:
# тип данных внутри
# напоминаем, массив numpy может хранить только один тип данных
a.dtype

dtype('int64')

### Изменение размеров массива

In [13]:
a = np.array([[1, 2, 3], [4, 5, 6]], int)

print(a)
print()

a.reshape(3,2)

[[1 2 3]
 [4 5 6]]



array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
# обратите внимание, что в процессе изменения размера создан новый массив, а не изменён старый
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# с помощью этой команды можно вытянуть массив в одномерную "строку"
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [ ]:
# ваш массив 3 на 3
# shape
# flatten
# print
# shape

In [ ]:
# обратите внимание, что в процессе изменения размера создан новый массив, а не изменён старый
a

array([[1, 2, 3],
       [4, 5, 6]])

### Создание по-разному заполненных массивов

In [17]:
np.zeros(3) # вся матрица из 0
np.ones(10) # вся матрица из 1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# аналог range для массивов
# arange(start, stop-1, step)
print(np.arange(5))
print(np.arange(1, 6, 2))

[0 1 2 3 4]
[1 3 5]


In [21]:
range(1.3, 6, 0.5)

TypeError: ignored

In [20]:
np.arange(1.3, 6, 0.5)

array([1.3, 1.8, 2.3, 2.8, 3.3, 3.8, 4.3, 4.8, 5.3, 5.8])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# k - номер диагонали, заполненный единицами
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

### Перебор элементов массива

In [22]:
a = np.array([1, 4, 5], int)

In [23]:
# простой перебор для одномерного случая
for x in a:
   print(x)

1
4
5


In [ ]:
# простой перебор для многомерного случая срабаотает плохо, он перебирает по первой размерности
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for x in a:
   print(x)

[1. 2.]
[3. 4.]
[5. 6.]


In [24]:
a = np.array([[1, 2], [3, 4], [5, 6]], int)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
a.shape

(3, 2)

In [ ]:
# перебор правильным способом
for x in range(a.shape[0]):
  for y in range(a.shape[1]):
    print(a[x, y])

1.0
2.0
3.0
4.0
5.0
6.0


In [ ]:
# Задание 3
# Создаете массив
# хотим пройтись по всем элементам
# сначала по столбцам
# потом по строчкам

## Операции над массивами

### Математические операции над массивами

С массивами можно применять стандартные математические операции. Они будут работать так, как будето происходит поэлементая работа одной и той же операции. Для матричных операций есть специальные команды.

**Стандартные математические операции применимы только к массивам одинаковых размеров.**

In [27]:
a = np.arange(1, 4, 1, dtype=int)
b = np.arange(6, 9, 1, dtype=int)
print('a: ', a)
print('b: ', b)

a:  [1 2 3]
b:  [6 7 8]


In [28]:
a + b

array([ 7,  9, 11])

In [29]:
a - b
# 1 - 6
# 2 - 7
# 3 - 8

array([-5, -5, -5])

In [30]:
b - a

array([5, 5, 5])

In [ ]:
a * b

array([ 6, 14, 24])

In [ ]:
b / a

array([6.        , 3.5       , 2.66666667])

In [ ]:
a % b

array([1, 2, 3])

In [31]:
print(a)
print(b)

[1 2 3]
[6 7 8]


In [ ]:
b**a
# 6**1
# 7**2
# 8**3

array([  6,  49, 512])

In [ ]:
a // b

array([0, 0, 0])

Кроме того, поэлементно могут быть применены другие математические операции

In [ ]:
# корень
# from math import sqrt 
# from numpy import sqrt

np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [32]:
a = np.array([1.1, 1.5, 1.9], float)

In [ ]:
# округление вниз
np.floor(a)

array([1., 1., 1.])

In [ ]:
# округление вврех
np.ceil(a)

array([2., 2., 2.])

In [ ]:
# округление по правилам математики
np.rint(a)

array([1., 2., 2.])

### Простые операции над массивами

#### Одномерные массивы

In [ ]:
a = np.arange(1, 6, 1)
print(a)
print('Сумма: ', a.sum())
print('Перемножение: ', a.prod())

[1 2 3 4 5]
Сумма:  15
Перемножение:  120


In [ ]:
# среднее (математическое ожидание)
a.mean()

3.0

In [ ]:
# дисперсия (смещенная - это будет важно в дальнейшем)
a.var()

2.0

In [ ]:
# стандартное отклонение (несмещенное - это тоже будет важно в дальнейшем)
a.std()

1.4142135623730951

In [33]:
a = np.array([1,56,-6,4])
a.min() # значение

-6

In [34]:
a.argmin() # индекс

2

In [ ]:
# clip позволяет "отрезать" значения сверху и снизу
a = np.array([6, 2, 5, -1, 0, 6, 2, 5, 4], float)
a.clip(0, 5)

array([5., 2., 5., 0., 0., 5., 2., 5., 4.])

In [35]:
np.unique(a)

array([ 1,  4, 15])

#### Многомерные массивы
Для работы с многомерными массивами можно использовать параметр `axis`.

In [ ]:
a = np.array([[5, 2], [4, 1], [3, -1]])
print(a)
print(a.mean(axis=0))
print(a.mean(axis=1))

[[ 5  2]
 [ 4  1]
 [ 3 -1]]
[4.         0.66666667]
[3.5 2.5 1. ]


### Логические операции над массивами

In [ ]:
a = np.array([1, 3, 0])
b = np.array([0, 3, 2])

print(a > b, type(a>b))

[ True False False] <class 'numpy.ndarray'>


In [ ]:
c = a == 0
c

array([False,  True, False])

In [ ]:
# проверяем, что хотя бы один элемент истинен
print(any(c))
# проверяем, что все элементы истинны
print(all(c))

True
False


Если вы хотите провести сравнение логическим И или лолгическим ИЛИ, то необходимо воспользоваться специальнымыми методами:


```
np.logical_and(_, _)
np.logical_or(_, _)
np.logical_not(_)
```



In [ ]:
a < 3 and a > 0

ValueError: ignored

In [ ]:
np.logical_and(a > 0, a < 3)

array([ True, False, False])

С помощью `np.where` можно создать массив на основании условий. 
Синтаксис:


```
where(boolarray, truearray, falsearray)
```



In [ ]:
np.where(a != 0, 1 / a, a)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([1.        , 0.33333333, 0.        ])

Можно проверять элементы массива на наличие NaN и бесконечностей.

In [38]:
a = np.array([1, np.NaN, np.Inf], float)
a

array([ 1., nan, inf])

In [40]:
np.isnan(a).sum()
# False = 0
# True = 1

1

In [ ]:
np.isfinite(a)

array([ True,  True,  True])

### Выбор элементов массива по условию

Очень важной особенностью массивов является то, что элементы в них можно брать на основании других массивов. Это особенно полезно при реализации свёрточных нейронных сетей.

In [ ]:
# это результат применения логической операции к многомерному массиву
a = np.array([[6, 4], [5, 9]], float)
a >= 6

array([[ True, False],
       [False,  True]])

In [ ]:
# а это результат фильтрации элементов
# обратите внимание, получился одномерный массив, содержащий только элементы, удовлетворяющие условию 
a[a >= 6]

array([6., 9.])

In [ ]:
a[np.logical_and(a > 5, a < 9)]

array([6.])

NumPy предлагает больше возможностей для индексирования, чем обычные последовательности Python. В дополнение к индексации целыми числами и срезами, как мы видели ранее, массивы могут индексироваться массивами целых чисел и массивами логических значений.

In [4]:
a = np.arange(12)**2  # the first 12 square numbers
print(a)

i = np.array([1, 1, 3, 8, 5])  # массив индексов
a[i]  # the elements of `a` at the positions `i`

[  0   1   4   9  16  25  36  49  64  81 100 121]


array([ 1,  1,  9, 64, 25])

In [6]:
j = np.array([[3, 4], [9, 7]])  # a bidimensional array of indices
a[j]  # the same shape as `j`

array([[ 9, 16],
       [81, 49]])

Обратите внимание, что если передать целочисленные значения, в качестве условий, то результат будет другой. Будут выбраные соответствующие элементы. 

In [ ]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
a[b]

In [ ]:
# Для выбора значений из многомерных массивов необходимо передать массивы, которые определяют индексы по каждому из направлений. Они должны быть, естественно, целочисленными.
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b,c]

array([ 1.,  4., 16., 16.,  4.])

## Векторная и матричная математика с использованием numpy

Векторная математика в numpy - это главная причина того, что numpy стал ключевым модулем Python среди всех представленных модулей. Векторные вычисления позволяют значительно ускорить обработку численной информации. 

Часто сравнивая Python c С++/C говорят том, что первый гораздо менее производителен. Но с учётом современных модулей верно следующее утверждение: хорошо написанная программа на Python будет производительнее, чем средняя программа на C/C++, хорошую программу на C/C++ написать крайне сложно. 

В дополнении к арифметически операциям мы рассмотрим некоторые векторные операции. Глубокое погружение в их суть требует значительных знаний математики, которые мы будем получать по мере необходимости. 

### Скалярное произведение

Для двух векторов a и b одинаковой длины скалярное произведение считается по следующей формуле:

$ a*b = \sum_{i=0}^{len(a)}  a_i*b_i $

In [ ]:
# скалярное произвдение векторов, также операция свёртки в свёрточных нейронных сетях 

a = np.array([1, 2, 3], float)
b = np.array([0, 1, 1], float)
np.dot(a, b)

5.0

### Произведение матриц

Произведение матриц - это особая математическая операция, которая не эквивалентна произведени соответствующих элементов матриц. О матричном произведении целесообразно говорить в рамках соответствующих разделов математики. Тем не менее, используя numpy легко получить матричное произведение.

In [ ]:
a = np.array([[0, 1], [2, 3]], float)
b = np.array([2, 3], float)
d = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]], float)

In [ ]:
np.dot(b, a)

array([ 6., 11.])

In [ ]:
np.dot(a, b)

array([ 3., 13.])

In [ ]:
# следите за размерностью, иначе ничего не получится
np.dot(b, d)

ValueError: ignored

### Определитель матриц

Многие математические операции, связанные с линейной алгеброй реализованы в модуле linalg внутри numpy. Мы не будем углулбляться в различные функциия модуля, рассмотрим для примера определитель. 

In [ ]:
np.linalg.det(a)

-2.0

# Дополнительный материал для желающих

[Несучный туториал по numpy](https://habr.com/ru/post/469355/)

# Задания

**Задание 1.** Создать матрицу размером `10х10` с 0 внутри, и 1 на границах. Например для `3х3`.

```
1 1 1
1 0 1
1 1 1
```
Количество строк кода идеального решения: 2  
Кроме print()

**Задание 2.** Создать 5x5 матрицу с 1,2,3,4 над диагональю. Все остальные элементы - 0.

Количество строк кода идеального решения: 1   
Кроме print()

**Задание 3.** Создайте случайную матрицу и вычтите из каждой строки среднее.
Количество строк кода идеального решения (кроме создания исходной матрицы): 1   
Кроме print()

In [ ]:
X = np.random.rand(5, 10)
Y =...

**Задание 4.**

Создать Массив размерностью (6,7). Поменять в массиве 3 строку с последней.

**Задание 5.**

Создать двумерный список и заполнить его рандомными числами. Преобразовать созданный список в NumPy массив (с типом int32).

**Задание 6.**

Создать массив размерностью (89, 67) и заполнить его случайными числами от -50 до 50. Посчитать количество ненулевых элементов полученного массива.

**Задача 7.**

Считайте 2 числа: n, m.

Создайте матрицу размера n*m и "раскрасьте" её в шахматную раскраску.

0 - "чёрное"

1 - "белое"

Ячейка с координатами (0, 0) всегда "чёрная" (т.е. элемент (0, 0) равен 0).
Матрицу сохраните в переменную Z.

**Задача 8.**

Вектор A содержит float числа как больше, так и меньше нуля.

Округлите их до целых и результат запишите в переменную Z. Округление должно быть "от нуля", т.е.:

положительные числа округляем всегда вверх до целого
отрицательные числа округляем всегда вниз до целого
0 остаётся 0

**Задача 9.**

Даны 2 вектора целых чисел A и B.

Найдите числа, встречающиеся в обоих векторах и составьте их по возрастанию в вектор Z.

Если пересечений нет, то вектор Z будет пустым.