In [2]:
import numpy as np

Номер 1

In [3]:
x = np.ones((10, 10))
x[1:9, 1:9] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Номер 2

In [4]:
x = np.diag([1, 2, 3, 4], k=1)
x

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

Номер 3

In [22]:
x = np.random.rand(5, 10)
x -= x.mean()
x

array([[ 0.46750622,  0.0796319 , -0.01228167, -0.33266374,  0.21406515,
        -0.2142737 , -0.39395994, -0.38452939, -0.43685429, -0.35964907],
       [ 0.35778355,  0.49532659,  0.35687039, -0.44967925,  0.19532528,
        -0.3015525 ,  0.1430614 ,  0.4366774 ,  0.11200221,  0.03716322],
       [ 0.44230769,  0.40960198,  0.21006496,  0.12347825, -0.41878143,
         0.06889914,  0.17268271, -0.28725618, -0.21905899, -0.25469449],
       [-0.29483489,  0.13401197, -0.40837542, -0.12944252, -0.32239668,
         0.36122531,  0.26718789, -0.48999673,  0.46170894, -0.11260012],
       [-0.26097782,  0.01004557, -0.00060528,  0.44766279,  0.23150134,
        -0.1736727 , -0.34406746,  0.21964969,  0.13324815,  0.01351457]])

Номер 4

In [6]:
x = np.random.rand(6,7)
temp = x[2].copy()
x[2] = x[-1]
x[-1] = temp
x

array([[0.34890928, 0.30281504, 0.79250082, 0.5548014 , 0.44157907,
        0.11794738, 0.24347212],
       [0.01004058, 0.9135295 , 0.55444319, 0.19652115, 0.65837902,
        0.11410409, 0.18612483],
       [0.96391744, 0.94632585, 0.41477382, 0.18854336, 0.37139103,
        0.13542152, 0.33608238],
       [0.64234813, 0.54163229, 0.03463542, 0.75711434, 0.0561455 ,
        0.31532612, 0.45273808],
       [0.01666815, 0.98683959, 0.71120219, 0.11569605, 0.94025283,
        0.05492113, 0.92645063],
       [0.75192005, 0.23741641, 0.74565012, 0.17491637, 0.58777564,
        0.15080831, 0.47027947]])

Номер 5

In [21]:
import random
a = []
for i in range(5):
   a.append([random.randint(0, 10) for j in range(5)])
q = np.array(a,dtype = np.int32)
q

array([[ 5,  3,  4,  9,  3],
       [ 6,  3,  3,  3,  6],
       [ 6,  0,  4,  2,  2],
       [ 7,  8, 10,  0,  4],
       [ 1, 10, 10,  8,  2]], dtype=int32)

Номер 6

In [20]:
q = np.random.randint(-50,51,size = (89,67))
print(q)
k = 0
for x in range(q.shape[0]):
  for y in range(q.shape[1]):
    if q[x,y] != 0:
      k += 1

[[-48 -46 -43 ...  -4  -5  -5]
 [  5 -46 -45 ...  11  18 -38]
 [ 18  19 -27 ... -16  16  40]
 ...
 [ 47 -50 -11 ...  -1 -36  -6]
 [ 20   1 -33 ...   3  15  32]
 [-28 -47  -1 ...  10  -2  31]]


Номер 8

In [19]:
q = np.array([0.0, 9.5, 13.3, -3.9, 368.3, 120.1, -907.0, -51.8, 16.6], float)
for i in range(len(q)):
  if q[i] > 0: 
    q[i] = np.ceil(q[i])
  else: 
    q[i] = np.floor(q[i])
print(q)

[   0.   10.   14.   -4.  369.  121. -907.  -52.   17.]


Номер 9

In [17]:
list1 = np.array([1,2,3,4,5,6,7,8,9,10])
list2 = np.array([0,2,0,6,0,4,0,8,0])
z = np.array([])
for i in list1:
  for j in list2:
    if i == j:
      z = np.append(z,i)
print(np.sort(z))

[2. 4. 6. 8.]
