In [ ]:
import numpy as np
import random

In [ ]:
sp = np.ones((10,10))
sp[1:-1, 1:-1] = 0
print(sp)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
sp = np.diag(np.arange(1, 5), k=1)
print(sp)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [ ]:
sp = np.random.rand(5, 10)
print(sp)

[[0.34725131 0.17581617 0.2058849  0.37477157 0.53744922 0.69156073
  0.62965617 0.05770544 0.15180814 0.79033394]
 [0.09401097 0.14267663 0.26396701 0.49045177 0.91427794 0.11355711
  0.61973368 0.37179589 0.21569289 0.38053366]
 [0.806622   0.08422735 0.54340402 0.42008518 0.40066023 0.0633795
  0.43148964 0.47890682 0.07084378 0.1629606 ]
 [0.21634602 0.53039769 0.89021891 0.98984102 0.17441316 0.72438917
  0.33245026 0.06543857 0.71889049 0.51799123]
 [0.2431896  0.87468453 0.1481988  0.58581906 0.37174493 0.30207924
  0.19643186 0.0751092  0.2906574  0.65499635]]


In [ ]:
print(sp.mean(1))

[0.39622376 0.36066976 0.34625791 0.51603765 0.3742911 ]


In [ ]:
sp = np.random.rand(6, 7)
print(sp)
print()
sp = sp[[0, 1, 5, 3, 4, 2], :]
print(sp)

[[0.36149922 0.99029964 0.12745038 0.44639567 0.33145973 0.55998297
  0.66013607]
 [0.47109272 0.12452537 0.36860869 0.21493298 0.77612513 0.58487094
  0.07210995]
 [0.47807706 0.62154507 0.93843193 0.95178997 0.27841474 0.39258679
  0.63424693]
 [0.74079324 0.8240601  0.94250983 0.87308309 0.72811332 0.27900528
  0.4513411 ]
 [0.31518641 0.91448969 0.88852753 0.37461954 0.39522211 0.76382058
  0.21037776]
 [0.85656565 0.97014745 0.72391159 0.48611333 0.24815101 0.7458456
  0.40033973]]

[[0.36149922 0.99029964 0.12745038 0.44639567 0.33145973 0.55998297
  0.66013607]
 [0.47109272 0.12452537 0.36860869 0.21493298 0.77612513 0.58487094
  0.07210995]
 [0.85656565 0.97014745 0.72391159 0.48611333 0.24815101 0.7458456
  0.40033973]
 [0.74079324 0.8240601  0.94250983 0.87308309 0.72811332 0.27900528
  0.4513411 ]
 [0.31518641 0.91448969 0.88852753 0.37461954 0.39522211 0.76382058
  0.21037776]
 [0.47807706 0.62154507 0.93843193 0.95178997 0.27841474 0.39258679
  0.63424693]]


In [ ]:
sp = [[0]*6 for i in range(7)]
for i in range(7):
  for j in range(6):
    sp[i][j] = random.randint(0, 25)
print(sp)
sp = np.array(sp, int)
print(sp)

[[13, 11, 4, 13, 20, 19], [21, 13, 19, 16, 22, 10], [1, 4, 20, 13, 17, 11], [23, 25, 20, 3, 21, 10], [5, 4, 22, 8, 8, 20], [15, 4, 7, 4, 23, 14], [15, 0, 1, 8, 17, 24]]
[[13 11  4 13 20 19]
 [21 13 19 16 22 10]
 [ 1  4 20 13 17 11]
 [23 25 20  3 21 10]
 [ 5  4 22  8  8 20]
 [15  4  7  4 23 14]
 [15  0  1  8 17 24]]


In [ ]:
sp = np.random.randint(-50, 51, (89, 67))
sp = sp[sp != 0]
print(len(sp))

5889


In [ ]:
n, m = map(int, input().split())
sp = np.ones((m, n))
sp[0:m:2, 0:n:2] = 0
sp[1:m-1:2, 1:n-1:2] = 0
print(sp)

7 3
[[0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0.]]
