In [102]:
#N1
import numpy as np
a = np.ones((10,10))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [103]:
#N2
a = np.diag([1, 2, 3, 4], k=1) 
print(a)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [104]:
#N3
a = np.random.rand(5,10)
b = a - a.mean()
print(a)
print('_________________________________________________________________________')
print(b)

[[0.59091823 0.80862418 0.26383155 0.30594001 0.22549748 0.14519059
  0.80856637 0.8152596  0.28932678 0.04529816]
 [0.61891129 0.15285074 0.0016744  0.87674704 0.74655016 0.87285297
  0.66191251 0.2717053  0.95066741 0.12823322]
 [0.17699277 0.08871127 0.98153539 0.93123756 0.53953303 0.44859213
  0.14097983 0.77652178 0.97047005 0.40263287]
 [0.12797163 0.13916245 0.15625545 0.59046775 0.81708127 0.84087958
  0.96765527 0.49767814 0.9991141  0.24803872]
 [0.72806577 0.52145733 0.5562177  0.21803357 0.74748436 0.91144912
  0.45793945 0.32465665 0.09700904 0.29313732]]
_________________________________________________________________________
[[ 0.08536785  0.30307379 -0.24171884 -0.19961038 -0.2800529  -0.3603598
   0.30301598  0.30970922 -0.2162236  -0.46025223]
 [ 0.1133609  -0.35269965 -0.50387599  0.37119665  0.24099978  0.36730259
   0.15636212 -0.23384509  0.44511702 -0.37731717]
 [-0.32855762 -0.41683911  0.475985    0.42568717  0.03398264 -0.05695826
  -0.36457055  0.2709714   

In [105]:
#N4
a = np.random.rand(6,7)
print(a)
print('___________________________________________________________________')
a[[0,2]] = a[[0,5]]
print(a)

[[6.38949833e-01 2.23339603e-01 3.33684768e-01 9.31537997e-01
  3.25804961e-01 1.16591071e-01 3.00668678e-01]
 [6.01539979e-01 6.17561183e-01 8.46525277e-01 5.68927998e-01
  8.40987616e-01 6.04651441e-01 9.42811841e-01]
 [7.69236661e-01 3.90104989e-01 5.65368025e-01 6.36259001e-02
  9.36296591e-01 6.89186186e-01 9.15640584e-01]
 [2.76525316e-01 4.33694277e-01 9.29965449e-01 7.84296251e-01
  6.81897965e-04 5.51543068e-01 6.41998853e-01]
 [2.38708076e-01 9.50509202e-01 5.64158132e-03 6.44242434e-01
  3.43442587e-01 3.80624065e-01 3.31488617e-01]
 [1.58807762e-01 8.26671998e-03 3.47153924e-01 4.21586195e-01
  4.86864304e-01 9.10114555e-01 7.23057640e-01]]
___________________________________________________________________
[[6.38949833e-01 2.23339603e-01 3.33684768e-01 9.31537997e-01
  3.25804961e-01 1.16591071e-01 3.00668678e-01]
 [6.01539979e-01 6.17561183e-01 8.46525277e-01 5.68927998e-01
  8.40987616e-01 6.04651441e-01 9.42811841e-01]
 [1.58807762e-01 8.26671998e-03 3.47153924e-01 4.21

In [106]:
#N5
a = np.random.rand(4)
print(type(a))
b = a.astype(int)
b

<class 'numpy.ndarray'>


array([0, 0, 0, 0])

In [107]:
#N6
a = np.random.randint(-50, 50, size = (89, 67)) 
print(a)

[[-47 -40  -8 ...  26 -42 -30]
 [ 47 -22  -7 ... -24   0 -17]
 [ 30  36 -24 ... -28  44 -24]
 ...
 [-46 -43  36 ...  24 -36   8]
 [-14  14  48 ...  46  34 -43]
 [  8  28 -49 ... -41 -41  42]]


In [108]:
#7
n = int(input())
m = int(input())
a = np.zeros((n,m))
a[1::2, ::2] = 1 
a[::2, 1::2] = 1
print(a)


2 
3
[[0. 1. 0.]
 [1. 0. 1.]]


In [109]:
#N8
a = np.array([1.2, -10.3, 5.3, 6.4, -6.3, -3.4, 0], float)
for i in range(len(a)):
  if a[i]>0: 
    a[i]=np.ceil(a[i])
  elif a[i]<0: 
    a[i]=np.floor(a[i])
  else:
    a[i]=0
print(a)

[  2. -11.   6.   7.  -7.  -4.   0.]
