In [42]:
import numpy as np

Номер 1




In [43]:
a = np.ones((10,10), int)
a[1:9,1:9]=0
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

Номер 2

In [47]:
a = np.diag([1, 2, 3, 4], k=1)
a

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

Номер 3

In [45]:
a = np.random.rand(5, 10)
a-=a.mean()
a

array([[ 0.41705846, -0.02189941,  0.4021004 , -0.38931288, -0.39785345,
         0.42494106,  0.36399443, -0.24104316, -0.16065478, -0.20980377],
       [ 0.08008859,  0.12906009,  0.01670713, -0.12690639, -0.20609831,
         0.32614493,  0.44686534,  0.11390992, -0.05953017,  0.36731008],
       [-0.41528728, -0.11255831, -0.30556072, -0.12401941,  0.25637943,
        -0.19546382,  0.4806201 , -0.33352958,  0.25528549,  0.06259792],
       [-0.05747836,  0.41956753, -0.37985012, -0.16012238,  0.32147486,
         0.07878861, -0.00963761, -0.45023142,  0.06141337,  0.20249434],
       [ 0.07598599,  0.0476093 ,  0.18585289,  0.45711223, -0.3590681 ,
        -0.37698457, -0.43795785, -0.37416092,  0.20369195, -0.29204168]])

Номер 4

In [36]:
a = np.random.rand(6,7)
temp = a[2].copy()
a[2]=a[-1]
a[-1]=temp
a

array([[0.7919566 , 0.14922235, 0.68716289, 0.5442894 , 0.24534735,
        0.36346413, 0.00232986],
       [0.0478805 , 0.83645947, 0.35999007, 0.90669497, 0.1583667 ,
        0.29544545, 0.50676906],
       [0.51179529, 0.16861394, 0.64964465, 0.49302353, 0.63274446,
        0.2483871 , 0.36936153],
       [0.21613789, 0.99581226, 0.15424869, 0.32005059, 0.54786194,
        0.59650252, 0.59069119],
       [0.9965698 , 0.01041409, 0.46900582, 0.25646425, 0.01565184,
        0.03215363, 0.18353228],
       [0.86853207, 0.44276158, 0.18254932, 0.04284461, 0.57892454,
        0.80507403, 0.85444251]])

Номер 5

In [38]:
import random
a = [random.randint(0, 10) for i in range(10)]
b=np.array(a,dtype='i')
b

array([ 1,  9, 10,  3, 10,  3,  8,  8, 10, 10], dtype=int32)

Номер 6

In [ ]:
a = np.random.randint(-50,50, size = (89, 67))
print(a)

[[ 47   6 -15 ...  23  -6 -34]
 [-29  -7  -7 ...  37  42  47]
 [ 30 -22 -49 ... -36  46 -38]
 ...
 [ 34 -22   6 ... -17  47 -10]
 [ 21 -17  11 ...  -2 -45   0]
 [ 26 -39 -39 ...  21 -50 -19]]
[ -8  11  27  39 -13  39 -14 -28  22  42 -38 -29  42  32 -11  -9  22 -21
 -33  49  14 -31 -11  11  46 -28  35  -6  16 -27 -15 -27  43  13   5  30
  25  43  11 -35 -20   5   6 -36  33  33 -42 -14   7  -4 -35  30  19  22
  37 -27 -45 -13 -48 -49 -35  32  43  19 -10   8 -14]


Номер 7

In [ ]:
n = int(input())
m = int(input())
a = np.ones((n,m), int)
for i in range(n):
  for j in range(0,m,2):
    if i%2==0: a[i][j]=0
    else: a[i][j-1]=0
print(a)

5
10
[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]]


Задача 8.

Вектор A содержит float числа как больше, так и меньше нуля.

Округлите их до целых и результат запишите в переменную Z. Округление должно быть "от нуля", т.е.:

положительные числа округляем всегда вверх до целого отрицательные числа округляем всегда вниз до целого 0 остаётся 0

In [41]:
a = np.array([-5.2], float)
if a[0]>0: a=np.ceil(a)
elif a[0]<0: a=np.floor(a)
a

array([-6.])


Задача 9.

Даны 2 вектора целых чисел A и B.

Найдите числа, встречающиеся в обоих векторах и составьте их по возрастанию в вектор Z.

Если пересечений нет, то вектор Z будет пустым.

In [48]:
a = np.array([-5, 2,4,3,4,11], int)
b = np.array([11,4,3,4,2], int)
z = []
if len(a)>len(b):
  for i in b:
    c = np.where(a == i)
    if len(c[0])!=0 and (i in z)==False: z.append(i)
else:
  for i in a:
    c = np.where(b == i)
    if len(c[0])!=0 and (i in z)==False: z.append(i)
z.sort()
z

[2, 3, 4, 11]