n1


In [ ]:
import numpy as np

In [1]:
arr = np.ones((10, 10))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


n2


In [35]:
arr = np.diag(range(1,5), k=1)
print(arr)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


n3

In [5]:
arr=np.random.rand(3,4)
arr1=arr-arr.mean()
print(arr)
print(arr1)

[[0.92025087 0.50232488 0.16218878 0.15663135]
 [0.15215891 0.84947696 0.9846093  0.2171997 ]
 [0.9951364  0.80562039 0.28248223 0.13269122]]
[[ 0.40685329 -0.0110727  -0.35120881 -0.35676624]
 [-0.36123867  0.33607938  0.47121172 -0.29619788]
 [ 0.48173881  0.29222281 -0.23091535 -0.38070636]]


n4


In [41]:
arr=np.random.rand(6,7)
print(arr)
arr[[0,2]]=arr[[0,5]]
print(arr)

[[0.49485026 0.00923863 0.38617223 0.10214603 0.5645791  0.05223514
  0.03387371]
 [0.01514787 0.35184544 0.66603396 0.945806   0.04180876 0.45586299
  0.87229621]
 [0.77907997 0.95413275 0.43557976 0.43664323 0.8928012  0.76408009
  0.70732961]
 [0.71235918 0.08729043 0.80587812 0.01405574 0.20748534 0.16940915
  0.32157653]
 [0.00393991 0.57622594 0.8794986  0.86586705 0.84110195 0.12006543
  0.93034351]
 [0.08387706 0.82740093 0.8826584  0.04655711 0.74995579 0.50347059
  0.62361603]]
[[0.49485026 0.00923863 0.38617223 0.10214603 0.5645791  0.05223514
  0.03387371]
 [0.01514787 0.35184544 0.66603396 0.945806   0.04180876 0.45586299
  0.87229621]
 [0.08387706 0.82740093 0.8826584  0.04655711 0.74995579 0.50347059
  0.62361603]
 [0.71235918 0.08729043 0.80587812 0.01405574 0.20748534 0.16940915
  0.32157653]
 [0.00393991 0.57622594 0.8794986  0.86586705 0.84110195 0.12006543
  0.93034351]
 [0.08387706 0.82740093 0.8826584  0.04655711 0.74995579 0.50347059
  0.62361603]]


n5

In [12]:
x=[[64,32,1],[1,2,3]]
y=np.array(x,dtype = np.int32)
print(y)

[[64 32  1]
 [ 1  2  3]]


n6

In [34]:
arr = np.random.randint(-50,50, size = (89, 67))
print(arr)

[[  0  11  -6 ...  -4  12   9]
 [ 45 -26  47 ...  42 -16  34]
 [ 30  30   1 ...  -9 -31 -40]
 ...
 [-39 -45  -6 ...  37 -15  23]
 [ 42 -15  29 ...  -4 -27 -45]
 [-15  26 -14 ...  19 -15 -14]]


n7

In [27]:
n=int(input())
m=int(input())
arr=np.zeros((n,m))
arr[::2,1::2]=1
arr[1::2,::2]=1
print(arr)

5
5
[[0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]]


n8

In [45]:
arr = np.array([-5.2,-3.2,-9.8,3.2,5.2,9.8,0], float)
for i in range(len(arr)):
  if arr[i]>0: 
    arr[i]=np.ceil(arr[i])
  elif arr[i]<0: 
    arr[i]=np.floor(arr[i])
  else:
    arr[i]=0
print(arr)

[ -6.  -4. -10.   4.   6.  10.   0.]
