In [1]:
!pip install numpy
import numpy as np

Задача 1

In [61]:
a = np.ones((10,10))
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Задача 2 (Done)

In [ ]:
a = np.diag([1,2,3,4], 1)
for i in a

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

Задача 3 (Done)

In [21]:
x = np.random.rand(5, 10)
a = 0
m = x.mean()
for i in x:
  x[a] = i.mean() - m
  a += 1
print(x)

[[ 0.14254203  0.14254203  0.14254203  0.14254203  0.14254203  0.14254203
   0.14254203  0.14254203  0.14254203  0.14254203]
 [-0.05633849 -0.05633849 -0.05633849 -0.05633849 -0.05633849 -0.05633849
  -0.05633849 -0.05633849 -0.05633849 -0.05633849]
 [ 0.06355209  0.06355209  0.06355209  0.06355209  0.06355209  0.06355209
   0.06355209  0.06355209  0.06355209  0.06355209]
 [-0.06260055 -0.06260055 -0.06260055 -0.06260055 -0.06260055 -0.06260055
  -0.06260055 -0.06260055 -0.06260055 -0.06260055]
 [-0.08715508 -0.08715508 -0.08715508 -0.08715508 -0.08715508 -0.08715508
  -0.08715508 -0.08715508 -0.08715508 -0.08715508]]


Задача 4 (Done)

In [ ]:
a = np.random.rand(6, 7)
b = np.copy(a)
b

array([[0.82877269, 0.45221297, 0.08808513, 0.25891946, 0.83358724,
        0.4276195 , 0.09861454],
       [0.08406379, 0.1762034 , 0.59384299, 0.23098309, 0.47327198,
        0.30199721, 0.99705732],
       [0.39332293, 0.04617879, 0.26646708, 0.37546454, 0.87692308,
        0.46560088, 0.01757413],
       [0.22701831, 0.11127574, 0.98438897, 0.57952442, 0.43749989,
        0.07400853, 0.70281242],
       [0.0555235 , 0.53535212, 0.691234  , 0.99492271, 0.07133522,
        0.67995146, 0.43782852],
       [0.34508691, 0.21974082, 0.05052063, 0.8428663 , 0.49787425,
        0.50510512, 0.91656575]])

In [ ]:

a[2] = b[5]
a[5] = b[2]
a

array([[0.82877269, 0.45221297, 0.08808513, 0.25891946, 0.83358724,
        0.4276195 , 0.09861454],
       [0.08406379, 0.1762034 , 0.59384299, 0.23098309, 0.47327198,
        0.30199721, 0.99705732],
       [0.34508691, 0.21974082, 0.05052063, 0.8428663 , 0.49787425,
        0.50510512, 0.91656575],
       [0.22701831, 0.11127574, 0.98438897, 0.57952442, 0.43749989,
        0.07400853, 0.70281242],
       [0.0555235 , 0.53535212, 0.691234  , 0.99492271, 0.07133522,
        0.67995146, 0.43782852],
       [0.39332293, 0.04617879, 0.26646708, 0.37546454, 0.87692308,
        0.46560088, 0.01757413]])

Задача 5 (Done)

In [ ]:
X = np.random.rand(5)
a = X.astype('int32')
print(a)

[0 0 0 0 0]


Задача 6 (Done)

In [35]:
a = np.empty((89, 67), dtype = "int8")
amount = 0
for i in range(a.shape[0]):
  for j in range(a.shape[1]):
    a[i][j] = np.random.randint(-50, 51)
    if a[i][j] == 0:
      amount += 1
print(amount)

72


Задача 7 (Done)

In [41]:
n = int(input())
m = int(input())
z = np.empty((n,m))
for i in range(n):
  for j in range(m):
    if np.logical_or(np.logical_and(i % 2 == 0, j % 2 == 0),np.logical_and(i % 2 == 1, j % 2 == 1)):
      z[i][j] = 0
    else:
      z[i][j] = 1
z

10
5


array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int8)

Задача 8 (Done)

In [43]:
x = float(input())
y = float(input())
z = np.array([x,y] )
for i in range(z.shape[0]):
  if z[i] > 0:
    z[i] = np.ceil(z[i])
  else:
    z[i] = np.floor(z[i])
z

5.5
-4.1


array([ 6., -5.])

Задача 9 (Done)

In [58]:
a = np.array([1,2,3,4,6,5])
b = np.array([4,5,6,7,8,9,10])
z = np.array([])
for i in a:
  for j in b:
    if i == j:
      z = np.append(z, i)
print(z)
print(np.sort(z))

[4. 6. 5.]
[4. 5. 6.]
