In [19]:
import numpy as np

In [20]:
# Задание 1
a = np.array([[[1] * 10] + [[1] + [0] * 8 + [1]] * 8 + [[1] * 10]][0])
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [22]:
# Задание 2
b = np.array([[0, 1, 0, 0, 0], [0, 0, 2, 0, 0], [0, 0, 0, 3 , 0], [0, 0, 0, 0, 4], [0, 0, 0, 0, 0]])
b

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [31]:
# Задание 3
c = np.array([[0, 2, 3, 4], [1, 6, 7, 8]])
for i in range(c.shape[0]):
  print(np.mean(c[i]))

2.25
5.5


In [46]:
# Задание 4
d = [[1] * 7] * 3 + [[2] * 7] * 3
d = np.array(d[:2] + [d[-1]] + d[3:] + [d[2]])
d

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2],
       [1, 1, 1, 1, 1, 1, 1]])

In [53]:
# Задание 5
from random import randint
e = []
for i in range(4):
  e.append([randint(0, 100), randint(0, 100), randint(0, 100)])
e = np.array(e, "int32")
e

array([[97, 96, 74],
       [ 1, 40, 40],
       [15, 60,  4],
       [ 7, 15, 50]], dtype=int32)

In [57]:
# Задание 6
f = []
for i in range(89):
  b2 = []
  for i in range(67):
    b2.append(randint(-50, 51))
  f.append(b2)
f = np.array(f)
ct = 0
for x in range(f.shape[0]):
  for y in range(f.shape[1]):
    if f[x, y] != 0:
      ct += 1
ct

5888

In [60]:
# Задание 7
n, m = int(input()), int(input())
z = []
for i in range(n):
  z2 = []
  if i % 2 == 0:
    for i in range(m):
      if (i % 2 == 0):
        z2.append(1)
      else:
        z2.append(0)
  else:
    for i in range(m):
      if (i % 2 == 0):
        z2.append(0)
      else:
        z2.append(1)
  z.append(z2)
z = np.array(z)
z

8
8


array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [61]:
# Задание 8
import math

A = np.array([1, -0.43, 4.4, -3.45])
z = []
for i in A:
  if i >= 0:
    z.append(math.ceil(i))
  if i < 0:
    z.append(math.floor(i))
z

[1, -1, 5, -4]

In [70]:
# Задание 9
a = np.array([9, 2, 32, 56, 12])
b = np.array([5, 7, 15, 32, 2])
c2 = np.intersect1d(a, b)
c2.sort()
c2

array([ 2, 32])