In [2]:
import numpy as np

***Задание 1***
 
Создать матрицу размером 10х10 с 0 внутри, и 1 на границах. Например для 3х3.

1 1 1

1 0 1

1 1 1

In [ ]:
npArray1 = np.zeros((10, 10), int)
npArray1[0::9, ::] = npArray1[::, 0::9] = 1
print(npArray1)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


***Задание 2***

Создать 5x5 матрицу с 1,2,3,4 над диагональю. Все остальные элементы - 0.

Количество строк кода идеального решения: 1
Кроме print()

In [49]:
npArray2 = np.diag(range(1,5), k=1)
print(npArray2)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


***Задание 3***

Создайте случайную матрицу и вычтите из каждой строки среднее. Количество строк кода идеального решения (кроме создания исходной матрицы): 1
Кроме print()

In [6]:
npArray3 = np.random.rand(5, 10)
print(f'before mod : {npArray3}')
npArray3_modified = [npArray3[i] - npArray3[i].mean() for i in range(npArray3.shape[0])]
print(f'after mod : {npArray3_modified}')

before mod : [[0.07791049 0.7900536  0.45675417 0.00208565 0.21360948 0.59146365
  0.71421107 0.45906812 0.06076816 0.68584397]
 [0.32115517 0.01330955 0.08165572 0.33561692 0.57066251 0.43978579
  0.09281027 0.74524838 0.22230612 0.94458484]
 [0.36577162 0.82784473 0.11601309 0.82047886 0.56795685 0.52567589
  0.99518401 0.06272867 0.47032525 0.85113735]
 [0.69237082 0.84311797 0.36063825 0.61171703 0.48729523 0.87466224
  0.22626468 0.66123656 0.27129122 0.455304  ]
 [0.91327732 0.01962349 0.4143555  0.99435012 0.57783152 0.74382447
  0.93686891 0.77478617 0.85112867 0.26593191]]
after mod : [array([-0.32726634,  0.38487676,  0.05157733, -0.40309119, -0.19156736,
        0.18628681,  0.30903424,  0.05389129, -0.34440867,  0.28066713]), array([-0.05555835, -0.36340398, -0.2950578 , -0.0410966 ,  0.19394898,
        0.06307227, -0.28390326,  0.36853485, -0.15440741,  0.56787131]), array([-0.19454001,  0.2675331 , -0.44429854,  0.26016722,  0.00764522,
       -0.03463574,  0.43487238, -

***Задание 4.***

Создать Массив размерностью (6,7). Поменять в массиве 3 строку с последней.

In [10]:
npArray4 = np.random.rand(6, 4)
print(f"Before - \n{npArray4}") 
npArray4[2::3,::] = npArray4[5::-3,::]
print(f"After - \n{npArray4}") 


Before - 
[[0.92914084 0.41680372 0.1360087  0.00585335]
 [0.32331468 0.19686508 0.60991473 0.82372393]
 [0.71506166 0.97439366 0.41136405 0.55675485]
 [0.54325108 0.29061504 0.78134502 0.50463873]
 [0.72606703 0.16820344 0.21077341 0.64905526]
 [0.66000064 0.29447344 0.36952052 0.61034055]]
After - 
[[0.92914084 0.41680372 0.1360087  0.00585335]
 [0.32331468 0.19686508 0.60991473 0.82372393]
 [0.66000064 0.29447344 0.36952052 0.61034055]
 [0.54325108 0.29061504 0.78134502 0.50463873]
 [0.72606703 0.16820344 0.21077341 0.64905526]
 [0.71506166 0.97439366 0.41136405 0.55675485]]



***Задание 5.***

Создать двумерный список и заполнить его рандомными числами. Преобразовать созданный список в NumPy массив (с типом int32).

In [18]:
list5 = []
for i in range(4):
  list5.append([])
  for q in range(6):
    list5[i].append(np.random.randint(1, 9))

npArray5 = np.array(np.int32(list5), int)
print(npArray5)

[[2 3 5 2 2 1]
 [1 4 7 3 6 3]
 [1 5 3 2 2 1]
 [4 3 7 2 6 4]]


***Задание 6.***

Создать массив размерностью (89, 67) и заполнить его случайными числами от -50 до 50. Посчитать количество ненулевых элементов полученного массива.

In [45]:
npArray6 = np.array(np.random.rand(89, 67) * 100 - 50, int)
print(npArray6)
print(npArray6 != 0)
print(f'Колличество ненулевых - {np.array([npArray6 != 0], int).sum()}')

[[-15  43  10 ...  14  46   6]
 [-35  -4  18 ...  15  46  11]
 [-37  15 -13 ...  40 -46  31]
 ...
 [-21  17  -5 ...  46 -43  48]
 [ 44 -22 -44 ...  26   0  20]
 [ 31  24   2 ...  13 -12 -13]]
[[ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 ...
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True False  True]
 [ True  True  True ...  True  True  True]]
Колличество ненулевых - 5824


***Задача 7.***

Считайте 2 числа: n, m.

Создайте матрицу размера n*m и "раскрасьте" её в шахматную раскраску.

0 - "чёрное"

1 - "белое"

Ячейка с координатами (0, 0) всегда "чёрная" (т.е. элемент (0, 0) равен 0). Матрицу сохраните в переменную Z.

In [55]:
n = int(input())
m = int(input())

npArray7 = np.ones((n,m), int)

for i in range(n):
  for q in range(0,m,2):
    delta = int(i % 2)
    if (q + delta < m):
      npArray7[i, q + delta] = 0

print(npArray7)

5
7
[[0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]]



***Задача 8.***

Вектор A содержит float числа как больше, так и меньше нуля.

Округлите их до целых и результат запишите в переменную Z. Округление должно быть "от нуля", т.е.:

положительные числа округляем всегда вверх до целого, отрицательные числа округляем всегда вниз до целого, 0 остаётся 0

In [65]:
npArray8 = np.random.rand(10) * 100 - 50
print(npArray8)

for i in range(npArray8.shape[0]):
  if npArray8[i] > 0:
    npArray8[i] = np.ceil(npArray8[i])
  elif npArray8[i] < 0:
    npArray8[i] = np.floor(npArray8[i])
  else:
    npArray8[i] = 0

print(npArray8)

[ 24.10115493 -15.10903319 -48.2862659  -22.24911963  28.09319618
  -9.80157405  46.69199795  39.08150504 -46.69071773 -17.09090418]
[ 25. -16. -49. -23.  29. -10.  47.  40. -47. -18.]


***Задача 9.***

Даны 2 вектора целых чисел A и B.

Найдите числа, встречающиеся в обоих векторах и составьте их по возрастанию в вектор Z.

Если пересечений нет, то вектор Z будет пустым.

In [86]:
npArray9A = np.array(np.random.rand(10) * 10, int)
npArray9B = np.array(np.random.rand(10) * 10, int)
outVect = []

print(npArray9A)
print(npArray9B)

for i in range(10):
    if any(npArray9B == npArray9A[i]):
        outVect.append(npArray9A[i])

print(sorted(set(outVect)))

[9 0 3 5 2 0 3 0 7 0]
[4 9 5 4 9 1 6 3 4 6]
[3, 5, 9]
