In [2]:
import numpy as np

In [3]:
# task 1
a = np.ones((10,10))
a[1:9,1:9]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
# task 2
a = np.zeros((5,5))
for i in range(1, 5):
  a[i-1, i] = i
a 

array([[0., 1., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 4.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# task 3
X = np.random.rand(5, 10)
for i in range(5):
  for j in range(10):
    X[i][j] = X[i][j] - X.mean()
Y = X
Y

In [ ]:
# task 4
a = np.random.rand(6, 7)
def get_arr(arr):
  temp = []
  for el in arr:
    temp.append(el)
  temp = np.array(temp)
  return temp
temp_1 = get_arr(a[2])
temp_2 = get_arr(a[5])
a[2] = temp_2
a[5] = temp_1
a

In [ ]:
# task 5
import random
a = [[random.randint(1, 100) for x in range(5)] for x in range(5)]
a = np.array(a, dtype=np.int32)
a


array([[ 92,  98,  37,  66,  89],
       [ 75,  70,  60,  73,  60],
       [ 84,  41, 100,  92, 100],
       [ 99,  91,   7,  33,  16],
       [  9,  61,   9,  34,  15]], dtype=int32)

In [ ]:
# task 6
a = np.random.randint(-50, 50, (89, 67))
cnt = 0
for i in range(89):
  for j in range(67):
    if a[i][j] != 0:
      cnt += 1
cnt

5897

In [21]:
#task 7
n = int(input())
m = int(input())

c = np.ones((n,m), int)

for i in range(n):
  for j in range(0, m,2):
    if (j+ (i % 2) < m):
      c[i, j + (i % 2)] = 0

print(c)



5
7
[[0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]]


In [26]:
# task 8
a = np.random.rand(7) * 50 -np.random.rand(7)*50
print(a)

for i in range(a.shape[0]):
  if a[i] > 0:
    a[i] = np.ceil(a[i])
  elif a[i] < 0:
    a[i] = np.floor(a[i])
  else:
    a[i] = 0

print(a)

[ 16.62670213 -26.11766959   6.27767023 -19.53625341  -3.48808698
 -32.60510048  13.42646902]
[ 17. -27.   7. -20.  -4. -33.  14.]


In [59]:
a_1 = np.array(np.random.rand(7) * 10 - np.random.rand(7) * 10, int)
a_2 = np.array(np.random.rand(7) * 10 - np.random.rand(7) * 10, int)
Z = []

for i in range(7):
    if any(a_1 == a_2[i]):
        Z.append(a_2[i])

print(sorted(set(Z)))

[-4, 0]
