In [1]:
import numpy as np

1. Создать матрицу размером 10х10 с 0 внутри, и 1 на границах.

In [8]:
x = np.ones((10, 10))
x[1:9, 1:9] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


2. Создать 5x5 матрицу с 1,2,3,4 над диагональю. Все остальные элементы - 0.

In [9]:
t = np.diag((np.arange(5, 5)), k = 1)
print(t)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


3. Создайте случайную матрицу и вычтите из каждой строки среднее.


In [13]:
m = np.random.rand(5, 10)
n = m - m.mean()
print(m)
print(n)

[[0.12229328 0.92855735 0.31730599 0.56812323 0.66230311 0.97630657
  0.49051425 0.27618459 0.10676862 0.0623856 ]
 [0.21833933 0.32822505 0.63704518 0.14271202 0.21691638 0.69834843
  0.62653131 0.09816125 0.52562616 0.25459251]
 [0.72348706 0.46195026 0.40966276 0.73901095 0.90471985 0.57629137
  0.0942437  0.0590221  0.48451262 0.80756978]
 [0.2061582  0.03469658 0.09789543 0.15563414 0.87124816 0.5426034
  0.79099199 0.29723026 0.25440334 0.77465414]
 [0.11816345 0.53469139 0.40998737 0.36185675 0.55803649 0.75257391
  0.48565935 0.42504364 0.77425036 0.36331614]]
[[-0.32424282  0.48202125 -0.12923011  0.12158713  0.21576701  0.52977047
   0.04397815 -0.17035151 -0.33976748 -0.3841505 ]
 [-0.22819677 -0.11831105  0.19050908 -0.30382409 -0.22961972  0.25181233
   0.1799952  -0.34837485  0.07909006 -0.1919436 ]
 [ 0.27695095  0.01541416 -0.03687334  0.29247485  0.45818375  0.12975527
  -0.3522924  -0.38751401  0.03797652  0.36103367]
 [-0.2403779  -0.41183953 -0.34864067 -0.29090197 

4. Создать Массив размерностью (6,7). Поменять в массиве 3 строку с последней.

In [17]:
v = np.random.rand(6, 7)
v[[0, 2]] = v[[0, 5]]
print(v)

[[0.01217375 0.18041189 0.16789811 0.27474246 0.68266154 0.71075465
  0.81115605]
 [0.32715699 0.29700318 0.17278318 0.2836255  0.50316505 0.07084786
  0.9016004 ]
 [0.45097466 0.32315324 0.32895797 0.64248045 0.40191294 0.32335504
  0.88185098]
 [0.72311632 0.32256497 0.06357241 0.78715398 0.25535027 0.19392664
  0.79238431]
 [0.87022577 0.75270951 0.2904453  0.91572141 0.56657772 0.55987124
  0.77806104]
 [0.45097466 0.32315324 0.32895797 0.64248045 0.40191294 0.32335504
  0.88185098]]


5. Создать двумерный список и заполнить его рандомными числами.

In [20]:
a = [[1, 2, 3], [4, 5, 6]]
b = np.asarray(a, dtype = np.int32)
print(b, type(b))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


7. Считайте 2 числа: n, m.

Создайте матрицу размера n*m и "раскрасьте" её в шахматную раскраску.

0 - "чёрное"

1 - "белое"

Ячейка с координатами (0, 0) всегда "чёрная" (т.е. элемент (0, 0) равен 0). Матрицу сохраните в переменную Z.

In [28]:
n = int(input())
m = int(input())
z = np.zeros((n, m))
z[1::2, ::2] = 1
z[::2, 1::2] = 1
print(z)

3
5
[[0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]]


8. Вектор A содержит float числа как больше, так и меньше нуля.

Округлите их до целых и результат запишите в переменную Z. Округление должно быть "от нуля", т.е.:

положительные числа округляем всегда вверх до целого отрицательные числа округляем всегда вниз до целого 0 остаётся 0

In [30]:
a = np.array([[-2.3, 8.5, 3.6], [-1.2, 5.7, 0]], float)
b = np.trunc(a)
print(b)

[[-2.  8.  3.]
 [-1.  5.  0.]]


9. Даны 2 вектора целых чисел A и B.

Найдите числа, встречающиеся в обоих векторах и составьте их по возрастанию в вектор Z.

Если пересечений нет, то вектор Z будет пустым.

In [31]:
from numpy.lib.arraysetops import intersect1d
a = np.array([1, 2, 3, 4, 5, 6, 7], int)
b = np.array([1, 3, 5, 7, 9], int)
c = intersect1d(a, b)
print(c)

[1 3 5 7]
