In [2]:
import numpy as np

In [5]:
a = np.random.randint(-50,50, size = (89, 67))
n=0
for i in range(a.shape[0]):
  for j in range(a.shape[1]):
    if a[i][j]!=0: n+=1
print(a,n)

[[  1 -50 -29 ...   0  43 -29]
 [ -6 -34 -32 ... -24 -15 -30]
 [ 27   0  -7 ... -27  42  21]
 ...
 [  2 -35 -24 ...  44 -28 -23]
 [-21 -49 -19 ...  38  -1 -34]
 [-39  20 -42 ... -12  42 -30]] 5909
