In [13]:
#1
import numpy as np

a = np.ones((10, 10))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [17]:
#2
a = np.diag(range(1, 5), k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [20]:

#3
y= X - np.sum(X)
print(X)
print(y)

[[0.49032467 0.66362102 0.71143455 0.86566136 0.79629912 0.61464234
  0.07640011 0.99106393 0.13571603 0.89518519]
 [0.30852857 0.23848062 0.90847535 0.57073553 0.47498776 0.03183624
  0.84400011 0.32646296 0.44928502 0.57633291]
 [0.12495096 0.27842627 0.18944088 0.63881152 0.05630498 0.31762818
  0.66861367 0.738902   0.9397777  0.50063799]
 [0.58355244 0.28258864 0.13976941 0.50503487 0.23820038 0.34880218
  0.35091582 0.92712248 0.85329859 0.40560396]
 [0.28016405 0.43912322 0.10849332 0.39343235 0.42238982 0.32416652
  0.0562426  0.35568515 0.29060826 0.15527725]]
[[-22.39311415 -22.21981779 -22.17200426 -22.01777745 -22.0871397
  -22.26879648 -22.80703871 -21.89237488 -22.74772278 -21.98825362]
 [-22.57491024 -22.64495819 -21.97496346 -22.31270328 -22.40845105
  -22.85160257 -22.03943871 -22.55697585 -22.43415379 -22.3071059 ]
 [-22.75848785 -22.60501254 -22.69399794 -22.2446273  -22.82713384
  -22.56581063 -22.21482515 -22.14453681 -21.94366111 -22.38280083]
 [-22.29988637 -22.6

In [50]:
#4-?????
A = np.random.randint(0, 10, size=(6, 7))
print(A)
A[2,::]=A[5,::]

print("A1")
print(A)

[[6 1 2 7 0 3 5]
 [1 8 1 1 3 5 0]
 [2 3 8 6 3 4 4]
 [5 5 0 1 0 3 7]
 [7 1 1 0 1 8 4]
 [6 0 1 4 8 8 3]]
A1
[[6 1 2 7 0 3 5]
 [1 8 1 1 3 5 0]
 [6 0 1 4 8 8 3]
 [5 5 0 1 0 3 7]
 [7 1 1 0 1 8 4]
 [6 0 1 4 8 8 3]]


In [54]:
#5
listx = []
for i in range(3):
  listx.append([])
  for q in range(6):
    listx[i].append(np.random.randint(0, 10))

arr = np.array(np.int32(list), int)
print(arr)

[[4 0 4 6 5 6]
 [6 3 6 8 7 9]
 [3 7 6 9 1 1]]


In [81]:
#6
A = np.random.randint(-50, 50, size=(89, 67))
x=np.array([A != 0], int).sum()
print(x)

5883


In [86]:
#7

n = int(input())
m = int(input())
x = np.ones((n,m))
x[0,0]=1
for i in range(n):
  for j in range(0,m,2):
    a = int(i % 2)
    if (j + a < m):
      x[i, j + a] = 0
print(x)

4
4
[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]
