**Задание 1.**

 Создать матрицу размером 10х10 с 0 внутри, и 1 на границах. Например для 3х3.

1 1 1

1 0 1

1 1 1

Количество строк кода идеального решения: 2
Кроме print()

In [ ]:
import numpy as np
arr = np.array([[1, 1, 1], [1, 0, 1], [1, 1, 1]], int)
arr

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

**Задание 2.** 

Создать 5x5 матрицу с 1,2,3,4 над диагональю. Все остальные элементы - 0.

Количество строк кода идеального решения: 1
Кроме print()

In [3]:
import numpy as np
arr = np.diag(np.arange(1, 5), k=1)
arr

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])


 **задание 3.**

Создайте случайную матрицу и вычтите из каждой строки среднее. Количество строк кода идеального решения (кроме создания исходной матрицы): 1
Кроме print()

In [2]:
import numpy as np
arr=np.random.rand(3,4)
arr1=arr-arr.mean()
print(arr)
print(arr1)

[[0.53281903 0.09740751 0.72302009 0.65526448]
 [0.67570047 0.82343831 0.7302921  0.21174583]
 [0.66632248 0.95158295 0.3274     0.20004978]]
[[-0.01676789 -0.45217941  0.17343317  0.10567756]
 [ 0.12611355  0.27385139  0.18070518 -0.33784109]
 [ 0.11673556  0.40199603 -0.22218692 -0.34953714]]


**Задание 4.**

Создать Массив размерностью (6,7). Поменять в массиве 3 строку с последней.

In [3]:
import numpy as np
z = np.random.random((6,7))
print(z)
z[[0,2]]=z[[0,5]]
print(z)


[[0.18674333 0.40747553 0.25849598 0.02148929 0.62784693 0.18211291
  0.3233692 ]
 [0.93164305 0.91272368 0.72972707 0.53233633 0.45907481 0.34157449
  0.4068263 ]
 [0.05937955 0.13202533 0.74084294 0.23202693 0.94115063 0.14980038
  0.38138906]
 [0.0789802  0.79027709 0.06261793 0.71919654 0.83662388 0.91489294
  0.67782602]
 [0.7147042  0.6404951  0.38450433 0.57224528 0.30106946 0.22319488
  0.22143904]
 [0.6491798  0.43734487 0.85322163 0.42426101 0.94547243 0.33172397
  0.7161504 ]]
[[0.18674333 0.40747553 0.25849598 0.02148929 0.62784693 0.18211291
  0.3233692 ]
 [0.93164305 0.91272368 0.72972707 0.53233633 0.45907481 0.34157449
  0.4068263 ]
 [0.6491798  0.43734487 0.85322163 0.42426101 0.94547243 0.33172397
  0.7161504 ]
 [0.0789802  0.79027709 0.06261793 0.71919654 0.83662388 0.91489294
  0.67782602]
 [0.7147042  0.6404951  0.38450433 0.57224528 0.30106946 0.22319488
  0.22143904]
 [0.6491798  0.43734487 0.85322163 0.42426101 0.94547243 0.33172397
  0.7161504 ]]


**Задание 5.**

Создать двумерный список и заполнить его рандомными числами. Преобразовать созданный список в NumPy массив (с типом int32).

In [5]:
import random
import numpy as np
a=[]
for i in range(5):
   a.append([random.randint(0, 100) for _ in range(5)])
b=np.array(b,dtype = np.int32)
print(type(a))
print(type (b))

<class 'list'>
<class 'numpy.ndarray'>


**Задание 6.**

Создать массив размерностью (89, 67) и заполнить его случайными числами от -50 до 50. Посчитать количество ненулевых элементов полученного массива.

In [ ]:
z= np.random.randint(-50, 50, size=(89, 67))
c=0
for x in range(z.shape[0]):
  for y in range(z.shape[1]):
    if z[x, y]==0:
      c+=1
print(c)

59


**Задача 7.**

Считайте 2 числа: n, m.

Создайте матрицу размера n*m и "раскрасьте" её в шахматную раскраску.

0 - "чёрное"

1 - "белое"

Ячейка с координатами (0, 0) всегда "чёрная" (т.е. элемент (0, 0) равен 0). Матрицу сохраните в переменную Z.

In [6]:
import numpy as np
m=int(input())
n=int(input())
z=np.ones((m,n))
for x in range(z.shape[0]):
  for y in range(z.shape[1]):
    if y%2==0 and x%2==0:
      z[x, y]=0
    elif y%2==1 and x%2==1:
      z[x, y]=0
z


3
9


array([[0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0.]])

**Задача 8.**

Вектор A содержит float числа как больше, так и меньше нуля.

Округлите их до целых и результат запишите в переменную Z. Округление должно быть "от нуля", т.е.:

положительные числа округляем всегда вверх до целого отрицательные числа округляем всегда вниз до целого 0 остаётся 0

In [14]:
import numpy as np
arr = np.array([0.1, -4.2, 1.7, 8.9, -36.3], float)
for i in range(len(arr)):
  if arr[i]>0: 
    arr[i]=np.ceil(arr[i])
  elif arr[i]<0: 
    arr[i]=np.floor(arr[i])
  else:
    arr[i]=0
print(arr)



[  1.  -5.   2.   9. -37.]


**Задача 9.**

Даны 2 вектора целых чисел A и B.

Найдите числа, встречающиеся в обоих векторах и составьте их по возрастанию в вектор Z.

Если пересечений нет, то вектор Z будет пустым.